# Generated by Django 2.2 on 2019-05-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discutii',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discutii',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='starter',
        ),
        migrations.DeleteModel(
            name='Categorii',
        ),
        migrations.DeleteModel(
            name='Discutii',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
